- name: create Kubernetes home dir
  file:
    path: "/{{item}}"
    state: directory
    mode: '0755'
  with_items:
    - home/kubernetes
    - home/kubernetes/bin

- name: delete old stuff
  file: 
    path: "/{{item}}"
    state: absent
  with_items:
    -  usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf 
    
- name: Set files for GKE
  copy:
    dest: "/{{item}}"
    src: "{{item}}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - etc/systemd/system/kube-bootstrap-logs-forwarder.service
    - etc/systemd/system/kube-node-installation.service
    - etc/systemd/system/kube-node-configuration.service
    - etc/systemd/system/kube-container-runtime-monitor.service
    - etc/systemd/system/kubelet-monitor.service
    - etc/systemd/system/kube-logrotate.timer
    - etc/systemd/system/kube-logrotate.service
    - etc/systemd/system/kubernetes.target
    - etc/modprobe.d/sunrpc.conf
    - etc/cloud/cloud.cfg
    - lib/systemd/system/kubelet.service

- name: reload-systemd
  systemd:
    name: "{{item}}"
    enabled: true
    daemon_reload: true
  with_items:
    - kube-bootstrap-logs-forwarder.service
    - kube-node-installation.service
    - kube-node-configuration.service
    - kube-container-runtime-monitor.service
    - kubelet-monitor.service
    - kube-logrotate.timer
    - kube-logrotate.service
    - kubernetes.target
    - kubelet

- name: Set helper scripts
  copy:
    dest: "/{{item}}"
    src: "{{item}}"
    owner: root
    group: root
    mode: "0755"
  with_items:
    - home/kubernetes/configuration.sh
    - home/kubernetes/configuration-helper.sh
    - home/kubernetes/gke-internal-configuration-helper.sh

